/**
 * Authentication primitives for the admin server.
 *
 *  - Passwords are stored only as scrypt hashes (salted, memory-hard).
 *  - Verification is constant-time and does the same work for unknown users.
 *  - Sessions are random 256-bit ids kept server-side (only a SHA-256 of the id
 *    is stored), with idle and absolute expiry.
 *  - Each session has its own CSRF token for state-changing requests.
 *  - Login attempts are rate-limited per client IP with a temporary lockout.
 */
import { scrypt as scryptCb, randomBytes, timingSafeEqual, createHash } from 'node:crypto';
import { readFile, writeFile, mkdir, chmod } from 'node:fs/promises';
import { dirname } from 'node:path';

const SCRYPT = { N: 32768, r: 8, p: 1, keylen: 64 };
const MAXMEM = 128 * 1024 * 1024;

function scrypt(password, salt, keylen, opts) {
  return new Promise((resolve, reject) => {
    scryptCb(password, salt, keylen, opts, (err, key) => (err ? reject(err) : resolve(key)));
  });
}

export const PASSWORD_RULES = { minLength: 12, maxLength: 256 };

export function checkPasswordStrength(password) {
  const problems = [];
  if (typeof password !== 'string') return ['Password must be a string'];
  if (password.length < PASSWORD_RULES.minLength) problems.push(`Use at least ${PASSWORD_RULES.minLength} characters`);
  if (password.length > PASSWORD_RULES.maxLength) problems.push(`Use at most ${PASSWORD_RULES.maxLength} characters`);
  if (new Set(password).size < 5) problems.push('Use more varied characters');
  return problems;
}

/** Encoded format: scrypt$N$r$p$<salt base64>$<hash base64> */
export async function hashPassword(password) {
  const salt = randomBytes(16);
  const key = await scrypt(password.normalize('NFKC'), salt, SCRYPT.keylen, { N: SCRYPT.N, r: SCRYPT.r, p: SCRYPT.p, maxmem: MAXMEM });
  return ['scrypt', SCRYPT.N, SCRYPT.r, SCRYPT.p, salt.toString('base64'), key.toString('base64')].join('$');
}

export function parseHash(encoded) {
  const parts = String(encoded || '').split('$');
  if (parts.length !== 6 || parts[0] !== 'scrypt') return null;
  const [, N, r, p, salt, hash] = parts;
  const out = { N: Number(N), r: Number(r), p: Number(p), salt: Buffer.from(salt, 'base64'), hash: Buffer.from(hash, 'base64') };
  if (!(out.N >= 1024 && out.r >= 1 && out.p >= 1 && out.salt.length >= 16 && out.hash.length >= 32)) return null;
  return out;
}

// A fixed dummy hash so a missing/invalid configuration costs the same time.
const DUMMY = parseHash(`scrypt$${SCRYPT.N}$8$1$${Buffer.alloc(16, 7).toString('base64')}$${Buffer.alloc(64, 9).toString('base64')}`);

export async function verifyPassword(password, encoded) {
  const parsed = parseHash(encoded);
  const target = parsed || DUMMY;
  const key = await scrypt(String(password).normalize('NFKC'), target.salt, target.hash.length, {
    N: target.N,
    r: target.r,
    p: target.p,
    maxmem: MAXMEM,
  });
  const ok = key.length === target.hash.length && timingSafeEqual(key, target.hash);
  return Boolean(parsed) && ok;
}

/** Credentials come from ADMIN_PASSWORD_HASH (hosting) or the local credentials file. */
export async function loadPasswordHash({ file, env = process.env }) {
  if (env.ADMIN_PASSWORD_HASH) return parseHash(env.ADMIN_PASSWORD_HASH) ? env.ADMIN_PASSWORD_HASH : null;
  try {
    const data = JSON.parse(await readFile(file, 'utf8'));
    return parseHash(data.passwordHash) ? data.passwordHash : null;
  } catch {
    return null;
  }
}

export async function saveCredentials(file, passwordHash) {
  await mkdir(dirname(file), { recursive: true, mode: 0o700 });
  const data = { passwordHash, updatedAt: new Date().toISOString(), note: 'Generated by npm run admin:setup. Never commit this file.' };
  await writeFile(file, `${JSON.stringify(data, null, 2)}\n`, { mode: 0o600 });
  await chmod(file, 0o600).catch(() => {});
}

const sha256 = (v) => createHash('sha256').update(v).digest('hex');

export class SessionStore {
  constructor({ idleMs = 30 * 60 * 1000, absoluteMs = 8 * 60 * 60 * 1000, now = () => Date.now() } = {}) {
    this.idleMs = idleMs;
    this.absoluteMs = absoluteMs;
    this.now = now;
    this.sessions = new Map();
  }

  create() {
    const id = randomBytes(32).toString('base64url');
    const csrf = randomBytes(32).toString('base64url');
    const t = this.now();
    this.sessions.set(sha256(id), { csrf, created: t, seen: t });
    this.prune();
    return { id, csrf };
  }

  get(id) {
    if (!id || typeof id !== 'string' || id.length > 100) return null;
    const key = sha256(id);
    const s = this.sessions.get(key);
    if (!s) return null;
    const t = this.now();
    if (t - s.seen > this.idleMs || t - s.created > this.absoluteMs) {
      this.sessions.delete(key);
      return null;
    }
    s.seen = t;
    return s;
  }

  destroy(id) {
    if (id) this.sessions.delete(sha256(id));
  }

  destroyAll() {
    this.sessions.clear();
  }

  prune() {
    const t = this.now();
    for (const [k, s] of this.sessions) if (t - s.seen > this.idleMs || t - s.created > this.absoluteMs) this.sessions.delete(k);
  }
}

export function csrfMatches(session, token) {
  if (!session || typeof token !== 'string') return false;
  const a = Buffer.from(session.csrf);
  const b = Buffer.from(token);
  return a.length === b.length && timingSafeEqual(a, b);
}

export class LoginLimiter {
  constructor({ maxFailures = 5, windowMs = 15 * 60 * 1000, lockMs = 15 * 60 * 1000, now = () => Date.now() } = {}) {
    Object.assign(this, { maxFailures, windowMs, lockMs, now });
    this.entries = new Map();
  }

  /** @returns {{allowed:boolean, retryAfter:number}} retryAfter in seconds */
  check(key) {
    const e = this.entries.get(key);
    const t = this.now();
    if (!e) return { allowed: true, retryAfter: 0 };
    if (e.lockedUntil && e.lockedUntil > t) return { allowed: false, retryAfter: Math.ceil((e.lockedUntil - t) / 1000) };
    if (e.lockedUntil && e.lockedUntil <= t) this.entries.delete(key);
    else if (t - e.first > this.windowMs) this.entries.delete(key);
    return { allowed: true, retryAfter: 0 };
  }

  fail(key) {
    const t = this.now();
    let e = this.entries.get(key);
    if (!e || t - e.first > this.windowMs) e = { first: t, count: 0, lockedUntil: 0 };
    e.count++;
    if (e.count >= this.maxFailures) e.lockedUntil = t + this.lockMs;
    this.entries.set(key, e);
    return e;
  }

  success(key) {
    this.entries.delete(key);
  }
}
